project_id = "gitqiabjinsmxmwyatgf"

[functions.barcode-lookup]
verify_jwt = false

[functions.generate-eco-score]
verify_jwt = false

[functions.product-recognition]
verify_jwt = false

[functions.fetch-product-data]
verify_jwt = false

[functions.analyse-product]
verify_jwt = false

[functions.process-scan]
verify_jwt = false